name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
      - feat/episode-sorting # Remove this after merging to main
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy-supabase-functions.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Functions
        run: |
          # Deploy existing functions
          supabase functions deploy rss-feed \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          # Deploy translation functions
          supabase functions deploy translate-content \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          supabase functions deploy translate-content-claude \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          supabase functions deploy batch-translate \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: List deployed functions
        run: |
          supabase functions list \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy status notification
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Supabase Edge Functions deployed successfully!"
            echo ""
            echo "📡 RSS feeds are available at:"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/rss-feed"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/rss-feed/wtf"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/rss-feed/finance_transformers"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/rss-feed/cfo_memo"
            echo ""
            echo "🌐 Translation functions are available at:"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/translate-content"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/translate-content-claude"
            echo "- https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/batch-translate"
          else
            echo "❌ Deployment failed. Check the logs above for details."
          fi